name: Deploy to Self-Hosted Server via DockerHub

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ratchaphongc1/ec2-jarmal-image-round-2:latest .

      - name: Push Docker Image to DockerHub
        run: docker push ratchaphongc1/ec2-jarmal-image-round-2:latest

  deploy:
    name: Deploy to Self-hosted Server
    needs: build
    runs-on: self-hosted

    steps:
      - name: Free space before pull
        run: |
          docker ps -aq --filter status=exited | xargs -r docker rm -f || true
          docker image prune -a -f || true
          docker builder prune -af || true
          df -h || true
          docker system df || true

      - name: Pull latest image from DockerHub
        run: docker pull ratchaphongc1/ec2-jarmal-image-round-2:latest

      - name: Stop and remove old container (if exists)
        run: docker rm -f ec2-jarmal-container-round-2 || true

      - name: Create .env file on the server
        run: |
          {
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}";
            # echo "PORT=4000";
            # echo "NODE_ENV=production";
          } > .env

      - name: Run new container
        run: |
          docker run -d \
            -p 4000:4000 \
            --env-file .env \
            --name ec2-jarmal-container-round-2 \
            --restart unless-stopped \
            ratchaphongc1/ec2-jarmal-image-round-2:latest \
            sh -c "npx prisma migrate deploy && npx prisma generate && node dist/src/main.js"
